services:
  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  # Redis Cache
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

  # Express API
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 8080
      ACCESS_TOKEN_SECRET: access
      REFRESH_TOKEN_SECRET: refresh
      ACCESS_TOKEN_EXPIRATION: 15m
      REFRESH_TOKEN_EXPIRATION: 259200
      MONGODB_URI: mongodb://mongodb:27017/organization
      REDIS_URI: redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb: {}
