services:
  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  # Redis Cache
  redis:
    image: redis:alpine
    restart: always
    command: sh -c "sysctl vm.overcommit_memory=1 && redis-server"
    privileged: true

  # Express API
  api:
    build: .
    ports:
      - 10000:10000
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb: {}
