services:
  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  # Redis Cache
  redis:
    image: redis:alpine
    restart: always
    command: sh -c "sysctl vm.overcommit_memory=1 && redis-server"
    privileged: true

  # Express API
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      HOST: 127.0.0.1
      PORT: 8080
      ACCESS_TOKEN_SECRET: access
      REFRESH_TOKEN_SECRET: refresh
      ACCESS_TOKEN_EXPIRATION: 2m
      REFRESH_TOKEN_EXPIRATION: 300
      MONGODB_URI: mongodb://mongodb:27017/organization
      REDIS_URI: redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb: {}
