services:
  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  # Express API
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 8080
      ACCESS_TOKEN_SECRET: access
      REFRESH_TOKEN_SECRET: refresh
      ACCESS_TOKEN_EXPIRATION: 15m
      MONGODB_URI: mongodb://mongodb:27017/organization
    depends_on:
      - mongodb

volumes:
  mongodb: {}
